spring:
  profiles:
    active:
    - develop

---
spring:
  config:
    activate:
      on-profile:
      - develop
  h2:
    console:
      enabled: false
      path: /h2
  datasource:
    url: jdbc:h2:file:./developDb
    driver-class-name: org.h2.Driver 
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
logging:
  level:
    root: DEBUG
    '[org.springframework.security]': DEBUG
---
spring:
  config:
    activate:
      on-profile:
      - database
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:./demo
    username: sa
    password:
    driver-class-name: org.h2.Driver 
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
logging:
  level:
    root: DEBUG
    '[org.springframework.security]': DEBUG
---
spring:
  config:
    activate:
      on-profile:
      - test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop 
    properties:
      dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: false
  sql:
    init:
      mode: always
logging:
  level:
    root: ERROR
    '[org.springframework.security]': DEBUG


